### ISSUE TITLE
Implement a bootstrap function

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#10]
Implement a function that allows user-friendly bootstrapping. 

Interessting packages to look at:

- The [boot package](https://cran.r-project.org/web/packages/boot/index.html)
- The [rsample package](https://github.com/topepo/rsample/tree/master)

**Comment by FloSchuberth** [comment]
See also the Jackknife function that I wrote for the MoMpoly package. Moreover make sure that one is able to control for outliers and inadmissible results during bootstrap.

**Comment by FloSchuberth** [comment]
Moreover, indirect effects should be bootstrapped to, see Nitzl et al. 2016

**Comment by M-E-Rademaker** [comment]
fixed by #148
