### ISSUE TITLE
Implement Conbach's alpha (including closed form CI)

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#104]
Wenn wir Cronbach's alpha implementieren sollten wir uach die geschlossenen Konfidenzintervalle implementieren. 

Laura Trinchera Laura Trinchera Nicolas Marie Nicolas Marie George A. Marcoulides (2017) - A Distribution Free Interval Estimate for Coefficient Alpha Structural Equation Modeling A Multidisciplinary Journal.

**Comment by FloSchuberth** [comment]
We can also use the alpha function of the psych package

**Comment by FloSchuberth** [comment]
A code for the distribution free CIs is provided in the Appendix of Laura's publication

**Comment by M-E-Rademaker** [comment]
will be addressed in when implementing the `assess()` function

**Comment by FloSchuberth** [comment]
Is implemented in 000_new
