### ISSUE TITLE
Should we change PLS to PLS-PM throughout the package?

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#128]
@FloSchuberth as you mentioned yesterday, it may be better to call the "weight estimator" PLS-PM in the print method for cSEMSummarize object. 

In this case, i think it would be consistent to replace PLS by PLS-PM throughout the package.

**Comment by FloSchuberth** [comment]
Do it ;)

**Comment by M-E-Rademaker** [comment]
then it call be done

**Comment by FloSchuberth** [comment]
:D
