### ISSUE TITLE
Allow for correction of the significance level to keep the familiy-wise error rate

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#138]
Fot test that are actually designed to compare two quantities, but are used for more than these two, the significance level should/must be adjusted (using e.g., the [Bonferroni correction](https://en.wikipedia.org/wiki/Bonferroni_correction))

Progress:

- [x] in `test_MGD()` if more than two groups are compared
- [x] CI for HTMT
- [x] in `test_MICOM()` if more than two groups are compared

**Comment by M-E-Rademaker** [comment]
closed via #381
