### ISSUE TITLE
Implement the empirical Bayes approach suggested by Dijkstra (2018) 

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#14]
Please implement the empirical Byes approach to control for Heywood cases, i.e., factor loadings larger than 1.

**Comment by M-E-Rademaker** [comment]
The relevant paper is [here](https://www.researchgate.net/publication/322331700_A_suggested_quasi_empirical_Bayes_approach_for_handling_'Heywood'-cases_very_preliminary?channel=doi&linkId=5a54cd6ca6fdcc51a61a5b22&showFulltext=true).

**Comment by FloSchuberth** [comment]
This should be done also in teh resmaple function see Section 2 of Dijkstra (2018)
