### ISSUE TITLE
Add additonal statistics to summary

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#142]
We should add additional statistics to the summarize function such as
- [x] R^2
- [x] adjusted R^2
- [x] VIF values
- [x] direct effect
- [x] indirect effect
- [x] total effect 
- [x] varriance accounted for (VAF)
- [ ] effect size f^2

**Comment by FloSchuberth** [comment]
direct effect, indirect effect, total effect, VAF, f^2, adj R^2

**Comment by M-E-Rademaker** [comment]
effect size will be implemented in #209
