### ISSUE TITLE
Implement Johnson Neyman intervals

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#151]
We shoudl implement Johnson Neyman intervals for interaction terms.

**Comment by FloSchuberth** [comment]
Reference: Spiller, Stephen A., et al. "Spotlights, floodlights, and the magic number zero: Simple effects tests in moderated regression." Journal of marketing research 50.2 (2013): 277-288.

**Comment by FloSchuberth** [comment]
I have a code snippet that can easily generalized...

**Comment by FloSchuberth** [comment]
A preliminary version for floodlight analysis is implemented in 000_new.r

**Comment by M-E-Rademaker** [comment]
implemented as `doFloodlightAnalysis()` and `plot.doFloodlightAnalysis()`
