### ISSUE TITLE
print testOMF

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#155]
I owuld repplace Dijsktra & Henseler (2015) by Beran & Srivastava (1985)

@Article{Beran1985,
  Title                    = {Bootstrap tests and confidence regions for functions of a covariance matrix},
  Author                   = {Beran, Rudolf and Srivastava, Muni S},
  Journal                  = {The Annals of Statistics},
  Year                     = {1985},
  Number                   = {1},
  Pages                    = {95--115},
  Volume                   = {13},
  Publisher                = {JSTOR}
}

**Comment by M-E-Rademaker** [comment]
But the test was proposed by Dijkstra & Henseler (2015) right? Wouldn't it make more sense to attribute it to them?

**Comment by FloSchuberth** [comment]
The test was originally proposed by Beran & Srivastava. Then it was reinvented by Bollen & Stine for SEM. Recently, the test was reinvented by Dijkstra & Henseler (2015) for PLS-PM. However we can also use the test in combination with MAXVAR, (e.g., Schuberth et al., 2018). 

Hence, I recommned to delete all referecnes from the print function and add them to the manual.
