### ISSUE TITLE
Checks of dataset

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#157]
I have used the satisfaction dataset which contains a character variable (gender). However, although I haven't specified an id, the estimation was conducted. There should occur an error message.

**Comment by FloSchuberth** [comment]
Or do we only consider the relevant variables, this is of course also an option. :)

**Comment by M-E-Rademaker** [comment]
We do it like this

- If there is a character column not given to `.id` there is an informative error message
- If there are other column of a type other than character whose name is not given to `.id` or used in the measurement model, then there will be no error.
