### ISSUE TITLE
missing in hetcor

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#169]
The treatment of missing vlaues should be listwise deletion.

**Comment by M-E-Rademaker** [comment]
Not sure if i understand correctly. Do you wnat the argument `use` to `hetcor` to be set to `"pairwise.complete.obs"`

**Comment by FloSchuberth** [comment]
Considering the hetcor function, we should not calculate SEs of the correlation as this requires times is not necessary for our purposes. Moreover, I checked the manual of the hetcor function and it seems that missing values are treated correctly, i.e., use is by default set to complete.obs
