### ISSUE TITLE
Implement tests for multigroup comparisons

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#17]
Please implement tests for multigroup comparison. In particular, those suggested by Chin and Dibbern (2010) and Klesel et al. (forthcomming).

Progress:

- [x] Klesel et al. (implemented as `test_MGD()` )
- [x] Chin and Dibbern (2010) - Chapter 7 in "Handbook of PLS"
- [ ] Sarsteadt et al. (2011) - Multigroup Analysis in Partial Least Squares ({PLS}) Path Modeling: Alternative Methods and Empirical Results

**Comment by FloSchuberth** [comment]
Currently we use the same settings for each dataset, i.e., we apply csem on  list of datasets. However, there may be situations where the settings differ across datasets. We should adjust the test function that we can compare one model across different datasets with differen specifications.

**Comment by M-E-Rademaker** [comment]
> 
> 
> Currently we use the same settings for each dataset, i.e., we apply csem on list of datasets. However, there may be situations where the settings differ across datasets. We should adjust the test function that we can compare one model across different datasets with differen specifications.

This wont be addressed as it would make implementation to complicated for a comparativly small benefit.

**Comment by FloSchuberth** [comment]
I agree.
