### ISSUE TITLE
Implement OrdPLSc

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#19]
Please implement OrdPLS as suggested by Schuberth et al. (2018). Therefore, you need to distinguish between ordinal and ratio/interval scaled variables. One way to do so, to provide the data as factors and then use one of the packgaes claculating the polyserial correlation. Im not sure yet whther this approach also works for non-linear models, perhaps for the approach where normality is assumed and then consider the underlying normally distributed variables. Might work.

**Comment by M-E-Rademaker** [comment]
fixed by #114
