### ISSUE TITLE
Implement fit and other assessment measures

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#21]
Implement common fit indices/measures and other measures used to assess a model (as part of the `assess()` function)

Progress:

- [x] Communality
- [x] Redundancy
- [ ] RMS_theta
- [ ] NFI
- [x] SRMR
- [x] dL
- [x] dG
- [x] AVE

**Comment by M-E-Steiner** [comment]
Indices to implement are:

- [ ] Communality
- [ ] Redundancy
- [ ] RMS theta

**Comment by FloSchuberth** [comment]
There are more:
NFI
SRMR
dL 
dG

**Comment by FloSchuberth** [comment]
Moreover, we need to implement the AVE for convergent validity...
