### ISSUE TITLE
Make resamplecSEMResults faster

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#221]
Resampling is still way too slow. I identified a couple of bottle necks

1. `ploycor::hetcor()` is apparently pretty slow. So we need to make sure that `stats::cor` is used when data is continious (which is probably the "normal" case)
2. `processData()` is also surprisingly slow. It doesnt matter so much when it is called once, but since it is part of `foreman()` it will be called on each resample although the checks are unnecessary because once the original data set has been checked and passed as ok, the resampled one's are ok too.
3. The real bottle neck, however, is `do.call()`. `do.call` is really bad on large objects. The larger the data set the slower it will get. So I need to find an alternative .

**Comment by FloSchuberth** [comment]
You could add an argument to process data, which is by default true and changes nothing, if it is set to false the function is skipped. If resample is applied you can set this argument to FALSE.
