### ISSUE TITLE
.user_funs does not work for objects of class "cSEMResults_2ndorder"

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#244]
Currently, the `.user_funs` argument only accepts functions of class `cSEMResults_default`, there should be an error when used on `cSEMResults_2ndorder` models. Eventually, it will be possible to use `cSEMResults_2ndorder` models as well. Until then, there must be an error.

**Comment by FloSchuberth** [comment]
does that also mean that user specified function are not allowed anymore or that user specified functions for second-order models do not work?

**Comment by M-E-Rademaker** [comment]
they just dont work when the original model is a Second order model. For any other model .user_fun works pretty nicely.

**Comment by FloSchuberth** [comment]
Got it :) However for the future this needs to be adjusted as users might for example calculate percentile bootstrap CIs for Cronbach's alpha

**Comment by M-E-Rademaker** [comment]
Agree. This will be possible once assess can be used as an argument to .user_funs
