### ISSUE TITLE
BasicCiResample() return strange confidence limits

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#248]
There is a bug in the function that computes the "Basic" confidence interval. 

```
model <- "
# Structural model
QUAL ~ EXPE
EXPE ~ IMAG
SAT  ~ IMAG + EXPE + QUAL + VAL
LOY  ~ IMAG + SAT
VAL  ~ EXPE + QUAL

# Measurement model
EXPE =~ expe1 + expe2 + expe3 + expe4 + expe5
IMAG =~ imag1 + imag2 + imag3 + imag4 + imag5
LOY  =~ loy1  + loy2  + loy3  + loy4
QUAL =~ qual1 + qual2 + qual3 + qual4 + qual5
SAT  =~ sat1  + sat2  + sat3  + sat4
VAL  =~ val1  + val2  + val3  + val4
"

a <- csem(satisfaction, model, .resample_method = "bootstrap")
summarize(a, .ci = "CI_basic")
```
returns the basic CI `[-2.1571;-0.5468] ` for the indirect effect of `SAT ~ EXPE`. This does not cover the 0 but the coefficient is close to zero.

**Comment by FloSchuberth** [comment]
for me it seems to work:

$Path_estimates$CI_percentile
     ETA3 ~ ETA1 ETA3 ~ ETA2 ETA3 ~ ETA1.ETA2
95%L   0.4787411  -0.3110475       -0.2231918
95%U   0.5036004  -0.2835234       -0.1942681
90%L   0.4813280  -0.3086138       -0.2215058
90%U   0.5016882  -0.2857522       -0.1965053

$Path_estimates$CI_basic
     ETA3 ~ ETA1 ETA3 ~ ETA2 ETA3 ~ ETA1.ETA2
95%L   0.4798175  -0.3139178       -0.2229683
95%U   0.5046768  -0.2863938       -0.1940446
90%L   0.4817296  -0.3116891       -0.2207310
90%U   0.5020899  -0.2888275       -0.1957306

**Comment by FloSchuberth** [comment]
Here with a true 0 path (ETA3~ETA1)

$Path_estimates$CI_percentile
      ETA3 ~ ETA1 ETA3 ~ ETA2 ETA3 ~ ETA1.ETA2
95%L -0.023358333  -0.2978430       -0.2072144
95%U  0.003754879  -0.2716273       -0.1777599
90%L -0.021634621  -0.2964395       -0.2052362
90%U  0.001577106  -0.2739521       -0.1799214

$Path_estimates$CI_basic
      ETA3 ~ ETA1 ETA3 ~ ETA2 ETA3 ~ ETA1.ETA2
95%L -0.023433091  -0.2979962       -0.2087696
95%U  0.003680121  -0.2717804       -0.1793152
90%L -0.021255318  -0.2956714       -0.2066081
90%U  0.001956409  -0.2731840       -0.1812934

**Comment by M-E-Rademaker** [comment]
ok seems to be fine.
