### ISSUE TITLE
Thoughts on how to distinguish between instruments/exogenous/endogenous/dependent/independent

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#251]
We discussed the best mechanism to identify which variables are instruments, which are exogenous etc.
The idea is:

1. introduce an argument ".instruments" (?). The argument is a named list with list names equal to the name of the dependent/endogenous/lhs-side variable  of each structrual equation (i.e, if there are 4 structural equations, `.instruments` will be a list of 4). 
2. Each list element is a character vector of instrument names. Possible ways to specfiy
   - `"~ z1 + z2 + z3"` (compare e.g. to `AER::ivreg()`
   - `"z1 + z2 + z3"`
   - `c("z1", "z2", "z3")` 

3. When parsing the model using `parseModel()` we check if `.instruments` is not `NULL` (the default). If it is not NULL `parseModel()` will add a new list element to the `cSEMModel` object. 
Probably we call this element `$instruments`.
4. `$instruments` is a list with as many elements as there are structural equations. For all equations that have no instruments the list element is `NULL`. All other equations contain a matrix similar to `$structural` with as many rows as there are endogenous variables (i.e. variable(s)
to instrument; note: make sure to use `drop = FALSE` when selecting) and as many columns as there are instruments.

Estimation:
- `estimatePathOLS` will probably be renamed to `estimatePath()`
- for the linear model: estimation is done by equation. Start by checking if  instruments exist for a given equation
- Run 2SLS or any other approach that we implemented.

Note: Why not use lavaan syntax: `lavaan::lavaanify()` does not have a straight-forward interface to supply instruments (something like `"eta1 ~ eta2 + eta3 | z1"` causes an error. Since we dont want to "hack" or rewrite how lavaan parses a model, we agreed its best to use an alternative way (as outlined above)

**Comment by FloSchuberth** [comment]
In addition, we need to exclude all the metrics that rely on R^2 if 2SLS is used as the R^2 is not meaningful anymore

**Comment by FloSchuberth** [comment]
Moreover, we should allow for feedback loops, as they can be estimated by 2SLS.

**Comment by FloSchuberth** [comment]
Allowing for feedback loops requires that parseModel is adjusted, currently an error occurs...
