### ISSUE TITLE
seed in resamplecSEMresults

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#257]
If no seed is supplied to the resamplecSEMresults function, in the information about resample, the .seed argument is set to FALSE. However, it would be nice to store there the seed that has been used. Although no seed is initially provided, internally I guess a seed is used.

This has the advantage that if you run bootstrap first without setting a seed, you can look afterwards in the information and replicate the results without setting the seed in advance.

**Comment by M-E-Rademaker** [comment]
Yes, but apparently there is no way to retrieve the seed if it is not explicitly set. I googled it but that was the conclusion after the search.

**Comment by FloSchuberth** [comment]
Then I recommend that we set a seed based on, e.g., the system time or a random generator
