### ISSUE TITLE
Bootstrap-based Hausman test for 3SLS vs 2SLS

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#262]
We need to figure out how the reference distribution is obtained in this case

**Comment by M-E-Rademaker** [comment]
Maybe we can extend the regression-based Hausman test to deal with 3SLS as well... should be possible in principle since its that same argument as for the OLS vs 2SLS case.

**Comment by FloSchuberth** [comment]
3SLS not implemented anymore
