### ISSUE TITLE
fit function for non-recursive models

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#264]
The fit function `fit()` does not work properly for models with feedback loops. The issue is likely the correlation between the zetas that is not taken into account.

This will be a long term plan. For now, a warning give indicating that the fitted VCV matrix is likely to be wrong.

**Comment by FloSchuberth** [comment]
For now we should return an error message if fit for non-recursive model is calculated

**Comment by FloSchuberth** [comment]
For default models, it should work now. However, models containing second-order constructs are still an open task

**Comment by M-E-Rademaker** [comment]
fixed
