### ISSUE TITLE
Print method testMGD issue

### ISSUE THREAD

**Issue by Klesel** [M-E-Rademaker/cSEM#287]
Currently, there is an error message:

Error in print.cSEMTestMGD(x) : object 'xs' not found.

Morover, the H0 description does not fit, if there are more than two groups.

**Comment by M-E-Rademaker** [comment]
The error has been fixed by my recent commit.

I’ll look into the H0 issue.

**Comment by M-E-Rademaker** [comment]
@Klesel why do you think the H0 is wrong?

**Comment by Klesel** [comment]
I would assume that when more than two groups are compared, that the H0 should acknowledge that, i.e. 
 |   H0: Parameter k is equal across three (and not two) groups.   |

**Comment by FloSchuberth** [comment]
I don’t agree as Chin & Dibbern always compares only two groups. So the H_0 of each test is whether a certain population is equal across 2 groups. Of course you can misuse their approach to make statement about other H_0s and adjust the p-values. Nevertheless, the H_0 per test is the same…

**Comment by M-E-Rademaker** [comment]
Which H0 are u talking about actually. I thought you meant the one for “Klesel”

**Comment by Klesel** [comment]
I wounder wether each test should refer to the same H0 or not...(my expectation would be that all tests refer to the same). Maybe missunderstood that ....

**Comment by FloSchuberth** [comment]
No, the tests refer to different H0s…So I think it is currently correct. You can test e.g., the H0 of Klesel et al. by the other if you adjust the significance level. But the H0 per test, i.e., for Chin & Dibbern and for Sarstedt et al., is unchanged.

**Comment by M-E-Rademaker** [comment]
issue is fixed. H0 is correct
