### ISSUE TITLE
.approach_weights naming of the approaches

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#308]
We should write the approaches unit and bartlett in capital, similar to the others.

**Comment by M-E-Rademaker** [comment]
I think it is more consistent to keep them as is. Reason:
1. `unit`, `bartelett`,  and `regression` are (as opposed to e.g. `PCA`, or `MAXVAR`) not abreviations.
2. Throughout the package all arguments are lower case (except for abreviations). Making them upper case would break this habit.

**Comment by FloSchuberth** [comment]
Alright, this is also fine with me.
