### ISSUE TITLE
print for cSEMResults object

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#314]
There is an issue in the print method if a list of parameters is provided as input:

res <- csem(.data = dat,
            .model = model,
            .approach_nl='sequential', 
.normality=T,
.resample_method = 'bootstrap',
.R = 100)

> res
________________________________________________________________________________
----------------------------------- Overview -----------------------------------

Estimation status by group/data set:

	Data_1            : successful
	Data_2            : successful
	Data_3            : successfulError in sum(status) : invalid 'type' (list) of argument

The same is true for default objects.

**Comment by M-E-Rademaker** [comment]
fixed by recent merge #319
