### ISSUE TITLE
HTMT does not work composites in case of the Bentiez (2020) data

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#346]

**Comment by FloSchuberth** [comment]
I think the problem is if not all indicators are positively correltaed, you can get negative average ave and thus NANs are produced, whcih creates problems for the print method

**Comment by M-E-Rademaker** [comment]
could you provide the data so I can replicate

**Comment by FloSchuberth** [comment]
Email is eigentlich schon raus…

**Comment by M-E-Rademaker** [comment]
i need the ben data not the MGA...or is that the benitz data?
