### ISSUE TITLE
Updates to calculateHTMT()

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#351]
To do

see pull request #374

**Comment by FloSchuberth** [comment]
Considering the inference we have to pay attention. For positive HTMT values the upper-bound is considered, while for negative HTMT values, the lower-bound needs to be considered. If we consider the absolute value of the HTMT only the upper-bound should be considered. 
An easy implementation might be to obtain the two-sided CI but multiply the alpha by 2 and report only the required bound, see above.
