### ISSUE TITLE
.PLS_mode = "unit" should not be disattenuated

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#352]
## 2. Compute consistent loadings and Q (Composite/proxy-construct correlation)
        ## for constructs modeled as common factors.
        for(j in names_cf) {
          Lambda[j, ] <- correction_factors[j] * W[j, ]
          Q[j]        <- c(W[j, ] %*% Lambda[j, ])
        }
I think the correction should only be done for modeB and modeA.

**Comment by FloSchuberth** [comment]
Yes, if PLS is employed, the correction should only be done for mode A and B. For now I suggested to ignore the correction for attenuation if weights are obtained by unit within the PLS algorithm
