### ISSUE TITLE
Write function to produce combined correlation matrix

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#353]
We should add a combined argument to the fit function, see email of Jörg

**Comment by M-E-Rademaker** [comment]
what do you mean by "combined correlation matrix". Does this refer to the email concerning the HTMT? 

lowertri = HTMT
uppertri = critical quantile?

**Comment by FloSchuberth** [comment]
No it is a wish by Jörg. I will take care of it…

**Comment by FloSchuberth** [comment]
see requested features
