### ISSUE TITLE
Implementation of RMS_theta incorrect?

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#368]
## Problem
There is something odd about the implementation of the RMS_theta.

When computed based on the population correlation matrix it is not zero. 

## Reason
RMS_theta and SRMR are acutally identical if used an index to assess the goodness of fit in "the SEM sense". See my notes on the RMS_theta.

## Action
- [ ] Remove RMS_theta 
- [ ] Note in the section on the SRMR the intuiton why this is the case

**Comment by FloSchuberth** [comment]
Let’s talk about that tmrw…
