### ISSUE TITLE
Extend testMGD function

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#377]
The test_MGD function needs to be extended and revised:

- [x] Show text/progress bar for bootstrap (via #359)
- [x] Implement CI comparisons
- [ ] Revise print methods
- [x] The argument of approach_mgd need to be added to the approach in the manual

**Comment by M-E-Rademaker** [comment]
You can skip the "show text/progress bar for bootstrap point". This has already been adressed by #359

**Comment by FloSchuberth** [comment]
Thx
________________________________
Von: Manuel Rademaker <notifications@github.com>
Gesendet: Samstag, 7. März 2020 20:56:53
An: M-E-Rademaker/cSEM
Cc: Schuberth, F. (ET); Assign
Betreff: Re: [M-E-Rademaker/cSEM] Extend testMGD function (#377)


You can skip the "show text/progress bar for bootstrap point". This has already been adressed by #359<https://github.com/M-E-Rademaker/cSEM/issues/359>
