### ISSUE TITLE
Fix testMGD function

### ISSUE THREAD

**Issue by Klesel** [M-E-Rademaker/cSEM#385]
There are some issues in the testMGD function

1. Some approches are not mentioned in the help file (e.g., Henseler)
2. the results using Henseler yield in no overall decision. This should be adressed. 
3. The procedure based on Sarstedt (comparison of a single path coeffient) does not have a named return vector (i.e., the decision is not named as in other procedures e.g., Chin).

**Comment by M-E-Rademaker** [comment]
Can you fix point 1 and 3 and open a pull request? 
I will look into point 2

**Comment by FloSchuberth** [comment]
ICh schau mir alle an...ist glaub ich einfacher....

**Comment by FloSchuberth** [comment]
@Klesel 
1) Habe die help file um Hnseler erweitert.
2) Hier müssen wir uns noch überlegen, was wir machen. Aber ich denke, dass ist im Moment in Ordnung. Henseler ist ein einsietiger test. Damit wir auf Gleichheit testen und der Benutzer nicht damit belästigt wird in welche Richtung getestet wird. Vergleiche ich den p-Wert mit alpha und 1-alpha. Es könnte nun aber sein, dass jmd nur in eine Richtung testen will und er erwartet, dass dies in der overall decision berücksichtigt wird. Dies ist aber nicht der Fall, daher werden NAs returned. 
3) Bei mir schon:
> out$Sarstedt$Decision
$none
$none$`1%`
C ~ A 
FALSE 

$none$`5%`
C ~ A 
FALSE 
Sieht auch ähnlich aus wie bspw. Chin:
> out$Chin$Decision
$none
$none$`1%`
$none$`1%`$`1_2`
C ~ A 
 TRUE 

$none$`1%`$`1_3`
C ~ A 
 TRUE

**Comment by Klesel** [comment]
Please not that you named the last part
`$none$1%$1_3 --> 1_3`

**Comment by FloSchuberth** [comment]
Naming for Chin is adjusted,

**Comment by FloSchuberth** [comment]
@M-E-Rademaker Can you merge issue_385 to master. Thanks

**Comment by M-E-Rademaker** [comment]
merged
