### ISSUE TITLE
Write print method for nonlineareffects analyis

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#392]
We need a print methid for floodlight anallysis. It should similiar to:
#> SIMPLE SLOPES ANALYSIS 
#> 
#> Slope of hp when wt = 2.24 (- 1 SD): 
#> 
#>    Est.   S.E.   t val.      p
#> ------- ------ -------- ------
#>   -0.06   0.01    -5.66   0.00
#> 
#> Slope of hp when wt = 3.22 (Mean): 
#> 
#>    Est.   S.E.   t val.      p
#> ------- ------ -------- ------
#>   -0.03   0.01    -4.07   0.00
#> 
#> Slope of hp when wt = 4.20 (+ 1 SD): 
#> 
#>    Est.   S.E.   t val.      p
#> ------- ------ -------- ------
#>   -0.00   0.01    -0.31   0.76

I would replace t val and p. by the lower and upper bound of the CI.

@M-E-Rademaker: Can you please let me know which input you require for this.

**Comment by M-E-Rademaker** [comment]
Ill let you know when I Look into it.

**Comment by FloSchuberth** [comment]
In issue 391 I have created a template for the new nonlineareffect function. The print method should be written for this function instead  of flood light analysis.
