### ISSUE TITLE
Adjust print testMGD

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#397]
We need to adjust the print method for Henseler in testMGD

**Comment by M-E-Rademaker** [comment]
What exactly needs to be adjusted?

**Comment by FloSchuberth** [comment]
I think the description of the test. 
At least I found one comment in the code:
    # Decision is made:
    # The probability is compared to alpha and 1-alpha
    # In doing so, we assess both hypotheses theta^1 <= theta^2 and 
    # theta^1 => theta^2
    # TRUE = p-value > alpha & p-value < 1-alpha --> not reject
    # FALSE = sufficient evidence against the H0 --> reject

However, in the text of the print it says:
Null hypothesis:

     +---------------------------------------------------------------------+
     |                                                                     |
     |   (1) H0: Parameter k of group 1 is smaller than that of group 2.   |
     |   (2) H0: Parameter k of group 1 is larger than that of group 2.    |
     |                                                                     |
     +---------------------------------------------------------------------+

I think that needs to be adjust. However, it is quite some time ago that I made this comment. Next time, I should add a bit description :)
