### ISSUE TITLE
testMGD return matrix with test results

### ISSUE THREAD

**Issue by Klesel** [M-E-Rademaker/cSEM#398]
It would be helpful to have a function that return the test results of the testMGD in a matrix.

**Comment by Klesel** [comment]
.parameters_to_compare is not in the return object.

**Comment by Klesel** [comment]
.parameters_to_compare is currently comparing everything per default. Since measurement invariance should be established before applying MGA the default should be the structural model only.

**Comment by FloSchuberth** [comment]
Ich glaub es wird per default nur das Strukturmodell verglichen. @Michael: Hast du das mal gecheckt?

**Comment by FloSchuberth** [comment]
Is this issue still open?
