### ISSUE TITLE
Hoelter N

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#411]
Implement Hoelter's N

**Comment by M-E-Rademaker** [comment]
Do you have a source for that. I found it on David A. Kennys website (<http://davidakenny.net/cm/fit.htm>). I'd implement this version.

**Comment by FloSchuberth** [comment]
this is fine

**Comment by M-E-Rademaker** [comment]
Implemented as `calculateCN()` using the formula from Bollen & Liang (1988) - Some properties of Hoelter's CN. 
Reason: Hoelter (1983) uses an approximation to the chi_square critical value; Bollen & Liang's formula is more exact (footnote 2 of the paper). The formula is the same as the one on Kennys website.
