### ISSUE TITLE
Blindfolding Q2^ not available!

### ISSUE THREAD

**Issue by areeq1** [M-E-Rademaker/cSEM#434]
Dear cSEM developer, thank you for your effort.
I noticed that Q2 blindfolding analysis (see Hair et al 2017, 2019) is missing in the current version of the package. It would be great if this analysis becomes available in the next update.
Thank you again,
Abdullah

Reference
Hair et al (2017). A Primer on Partial Least Squares Structural Equation Modeling

**Comment by M-E-Rademaker** [comment]
moved to #324; but currently not a priority
