### ISSUE TITLE
Error in testMICOM

### ISSUE THREAD

**Issue by srk7774** [M-E-Rademaker/cSEM#446]
``` r
library(cSEM)
#> Warning: package 'cSEM' was built under R version 4.0.5
#> 
#> Attaching package: 'cSEM'
#> The following object is masked from 'package:stats':
#> 
#>     predict
library(cSEM.DGP)
dgp1 <- "
# Structural model
Y ~ 0.6*X
# Measurement model
Y =~ 1*y1
X <~ 0.4*x1 + 0.8*x2
x1 ~~ 0.3125*x2
"
dgp2 <- "
# Structural model
Y ~ 0.6*X
# Measurement model
Y =~ 1*y1
X <~ 0.8*x1 + 0.4*x2
x1 ~~ 0.3125*x2
"
g1 <- generateData(dgp1, .N = 399, .empirical = TRUE) # requires cSEM.DGP
g2 <- generateData(dgp2, .N = 200, .empirical = TRUE) # requires cSEM.DGP
# Model is the same for both DGPs
model <- "
# Structural model
Y ~ X
# Measurement model
Y =~ y1
X <~ x1 + x2
"
# Estimate
csem_results <- csem(.data = list("group1" = g1, "group2" = g2), model)
# Test
testMICOM(csem_results, .R = 50, .alpha = c(0.01, 0.05), .seed = 1987)
#> Error in testMICOM(csem_results, .R = 50, .alpha = c(0.01, 0.05), .seed = 1987): unused argument (.alpha = c(0.01, 0.05))
```

<sup>Created on 2021-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by FloSchuberth** [comment]
Dear @srk7774, 

the reason why you get an error is because you specify .alpha argument. If you use the following, it works:
testMICOM(csem_results, .R = 50, .seed = 1987)

The testMICOM function just returns p-values and does not provide a decision. The decision needs to be done by you based on your assumed significance level.

Best regards, 
Florian

**Comment by srk7774** [comment]
Thanks, I got that.

**Comment by FloSchuberth** [comment]
Sure, you are welcome and please let us know if you face further problems with package.

Best regards,
Florian

**Comment by srk7774** [comment]
This Stone-Geisser’s Q^2 is similar to R^2 and calculated using the blindfolding procedure. . The following information helps to get an idea of how it can be done. Look the description part. The algorithm is clearly explained. https://www.smartpls.com/documentation/algorithms-and-techniques/blindfolding

After getting Q^2, we can also calculate q^2 which is effect size similar to f^2. Most papers report these results.

Currently, smartpls 2.0 is free and provides blindfolding option.
