### ISSUE TITLE
Mediation analysis for with multiple paths

### ISSUE THREAD

**Issue by grlju** [M-E-Rademaker/cSEM#457]
Hi cSEM team, 

Thanks a lot for a great package!

I have a question similar to: #435. In response to this question, you show how one can conduct a mediation analysis in a fairly simple model. My question is similar but distinct. 

Is there a way to test the mediation through a particular mediator when there are multiple mediators in the model?

If we take the following example:

```
require(cSEM)

set.seed(1234)
X_1 <- rnorm(100)
X_2 <- rnorm(100)
M_1 <- 0.1*X_1 + rnorm(100)
M_2 <- 0.3*X_2 + rnorm(100)
N_1 <- -0.1*X_2 + rnorm(100)
N_2 <- -0.2*X_1 + rnorm(100)
Y_1 <- 0.7*M_1 + 0.1*M_2 - 0.4*N_1 - 0.01*N_2 + 0.8*X_1 + 0.4*X_2 + rnorm(100)
Y_2 <- 0.3*M_1 + 0.01*M_2 - 0.06*N_1 - 0.07*N_2 + 0.1*X_1 + 0.6*X_2 + rnorm(100)
Data <- data.frame(Y_1 = Y_1, Y_2 = Y_2, X_1 = X_1, X_2 = X_2, M_1 = M_1, M_2 = M_2, N_1 = N_1, N_2 = N_2)

model <- '
# structural model
M ~ X
N ~ X

Y ~ M + N + X

# measurement model
Y <~ Y_1 + Y_2
X <~ X_1 + X_2
M <~ M_1 + M_2
N <~ N_1 + N_2
'

res <- csem(.data=Data,.model=model, .resample_method = "bootstrap", .R=100, .seed = 147150973)
summarize(res)
```
I can see the indirect effect. My understanding of this 'indirect effect' is that it is the effect of X on Y through both N and M. Is there a way of testing the portion that is mediated by either N or M separately. So testing if X -> M -> Y or X -> N -> M is significant.  

Thanks a lot for any ideas on this.

**Comment by FloSchuberth** [comment]
Dear @grlju,

Yes your understanding is correct, the indirect effect of x on Y is through both M and N. 
In cSEM there is no specific function to obtain only inference for a specific indirect effect. It is quite difficult to write a general function for that. However, you can obtain the inference as shown in the following:

# specify function that calculates a specific indirect effect, for instance: X -> M -> Y
indirectXonYviaM=function(.object){
  .object$Estimates$Path_estimates['M','X']*.object$Estimates$Path_estimates['Y','M']
}

# use this user-written function in csem.
res1=csem(.data=Data,.model=model, .resample_method = "bootstrap", .R=100, .seed = 147150973,.user_funs = indirectXonYviaM)

# Obtain CI
resinference=infer(res1,.quantity = 'CI_percentile')
resinference$User_fun
# please also see the help file for other CIs:
?infer

HTH 

Best regards, 
Florian

**Comment by grlju** [comment]
Hi Florian, 

Thanks a lot for the quick response. 

This works well for getting various path estimates and associated significance tests. 

After asking the question I also did some more searching and came across a function that does a mediation test using different methods and helps with interpreting the results [https://github.com/sergioventurini/SEMwPLS/blob/master/chapter5/code/R/mediate.R](url). When I use this function I get very similar results with the added benefit of being able to print these with the `mediate_print` function. However, by combining this with the user-supplied function approach you outlined one could avoid re-fitting the model using `systemfit` and re-calculating the SEs using `boot`. 

I can see that you also are also working on implementing conditional mediation, maybe the code in the above can help with this, at least in regards to testing and interpreting the mediation. 

Thanks again. 
Greg

**Comment by FloSchuberth** [comment]
Hey Grag,

You are welcome and thank you for pointing me to the mediate function. This is really nice. When I reviewed their code I was also puzzled why they use SUR instead of OLS as typically done in PLS-PM. In any case, I will see how I can implement this in cSEM.

The problem is of course as always time. The rest of the year I will be quite busy with teaching tasks, therefore, do not expect too much progress.

Best regards,
Florian
