### ISSUE TITLE
Modeling with ordinal variables

### ISSUE THREAD

**Issue by mantas-t** [M-E-Rademaker/cSEM#464]
I'm new to lavaan and cSEM. This might be already implemented in cSEM and I just didn't find a way how to do it.

Reproducible example and my attempts to do the same with cSEM are given below.

library(lavaan)
library(cSEM)

#ways to model ordinal data with lavaan:
#https://lavaan.ugent.be/tutorial/cat.html

N <- 1e5

#latent factors
F1 <- rnorm(N)
F2 <- rnorm(N)

#measurements for X
e_x1 <- rnorm(N)
x1 <- 1*F1 + e_x1

e_x2 <- rnorm(N)
x2 <- 0.5*F1 + e_x2

e_x3 <- rnorm(N)
x3 <- 1*F1 + e_x3

e_x4 <- rnorm(N)
x4 <- 1*F2 + e_x4

e_x5 <- rnorm(N)
x5 <- 0.25*F2 + e_x5

#measurements for Y
e_y <- rnorm(N)
y <- F1 + 0.5*F2 + e_y
yOrdinal <- ordered(ifelse(y<quantile(y,0.2),1,ifelse(y<quantile(y,0.5),2,3)))

data <- data.frame(x1,x2,x3,x4,x5,y,yOrdinal)

#SEM model, observable y is continious
model1 <- "
y_ ~ F1 + F2

F1 =~ x1 + x2 + x3
F2 =~ x4 + x5
y_ =~ y
"

#fitting with lavaan
res1SEM <- sem(data = data, model = model1)
summary(res1SEM)

#fitting withs cSEM
res1cSEM <- csem(.data = data, .model = model1)
summarize(res1cSEM)

#SEM model, observable y is ordinal (ordered)
model2 <- "
y_ ~ F1 + F2

F1 =~ x1 + x2 + x3
F2 =~ x4 + x5
y_ =~ yOrdinal
"

#fitting with lavaan
res2SEM <- sem(data = data, model = model2)
summary(res2SEM)
#lavaan does not like this type of model specification, however it provides point estimates

#fitting with cSEM
res2cSEM <- csem(.data = data, .model = model2)
summarize(res2cSEM)
#cSEM does not work at all

#different specification of the same model
model3 <- "
yOrdinal ~ F1 + F2

F1 =~ x1 + x2 + x3
F2 =~ x4 + x5
"

#fitting with lavaan
res3SEM <- sem(data = data, model = model3)
summary(res3SEM)
#lavaan works well with this specification and point estimates are the same as in the previous case

#fitting with cSEM
res3cSEM <- csem(.data = data, .model = model3)
#cSEM does not work with this model specification

**Comment by FloSchuberth** [comment]
Dear @mantas-t , 

in fact, we recently updated OrdPLS(c) and there was still a mistake. We fixed that and now your code runs. So please download the new master branch. 

Considering your last model specification

**Comment by mantas-t** [comment]
Thanks for such a quick fix! Have tried ant it works now.

One more question. I'm not sure how does OrdPLS(c) work so this might not be a proper question. Do you get some treshold estimates for different levels of y as in the usual oridinal logistic regression case? 

lavaan provides it.

Thresholds:
                   Estimate  Std.Err  z-value  P(>|z|)
    yOrdinal|t1      -0.842    0.045  -18.618    0.000
    yOrdinal|t2       0.000    0.040    0.000    1.000

**Comment by mantas-t** [comment]
thanks for the clarification!
