### ISSUE TITLE
Stadardization of the construct scores

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#49]
As discussed we should use different ways of calcuting the moments for linear and non-linear models. However, we als should use different ways of calculating the construct scores for linear and non-linear models. For non-linear we should the version from MoMpoly. For linear we should use XW'

**Comment by M-E-Steiner** [comment]
Idea for now is:

1. Scale data differently
    - If linear: use `scale()`
    - if nonlinear: use  
       ```     
       apply(X, 2, function(x) { 
       (x - mean(x)) / (stats::sd(x) * sqrt((length(x) - 1) / length(x)))
        })
       ```
  1.  Use `S = cor(X)` instead of `S = cov(X)`

**Comment by M-E-Rademaker** [comment]
directly related to #27
