### ISSUE TITLE
SIMULATE DATA

### ISSUE THREAD

**Issue by mcefis** [M-E-Rademaker/cSEM#492]
Good morning,

I want to ask you if it is included a simulation data function in your package? (or if you have scheduled to introduce it in the future).

Let me know if possible, many thanks

Mattia

**Comment by FloSchuberth** [comment]
Dear @mcefis, 

no the cSEM package itself does not include a simulation function to generate data. However, there is the cSEM.DGP package (https://m-e-rademaker.github.io/cSEM.DGP/) which can be used for that purpose. Alternatively, you can use lavaan. it also provides such a function. Finally, we are not planning to include such a function in the cSEM package.

Best regards, 
Florian
