### ISSUE TITLE
foreach

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#65]
Currently csem does not work with foreach. It does not find the model even if I provide it via .export. I think it has sth to do with storing the arguement and use the eval command...

**Comment by FloSchuberth** [comment]
Here is the problem with a potential solution, but not very nice:
https://stackoverflow.com/questions/19651274/doparallel-foreach-scoping-issue-error-in-evalexpr-envir-enclos-could-not

**Comment by FloSchuberth** [comment]
Perhaps the solution is to avoid the val command and use get or a similar command.

**Comment by M-E-Steiner** [comment]
yes, `get()` could work

**Comment by M-E-Steiner** [comment]
@FloSchuberth can you test my recent commit using `foreach`?
I hope that fixes the problem, although apparently the `eval(print(text = ""))` construct i used is not always optimal (see e.g., [this stackoverflow discussion](https://stackoverflow.com/questions/13649979/what-specifically-are-the-dangers-of-evalparse?noredirect=1&lq=1)). But i guess we can worry about that some other time..
