### ISSUE TITLE
Fix the testMICOM() function

### ISSUE THREAD

**Issue by M-E-Rademaker** [M-E-Rademaker/cSEM#69]
The function `testMICOM()` needs to be fixed as the package API has changed.

**Comment by FloSchuberth** [comment]
Was soll denn der input sein? .object oder wie bisher? Ich wuerde sie auf .object umschreiben…

**Comment by M-E-Steiner** [comment]
I agree, `testMICOM()` should take a cSEMResults object as input. So it should probably only have an `.object` argument

**Comment by M-E-Rademaker** [comment]
closed by #134
