### ISSUE TITLE
Permutate data function 

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#83]
We should write an own function to permute the data since permuting data is required for several tests. The input for this function should be a list of datasets. and the output should be a list with the permuted datasets.

**Comment by Klesel** [comment]
Is there a need for an exakt permutation test? (which is extremely computational intense)

**Comment by FloSchuberth** [comment]
No I do not think so, but if you have a straightforward way to achieve that you can add an extra argument to the function. For now, I think the normal permutation is fine.

**Comment by Klesel** [comment]
I pushed the permutation function. (permutateData <- function(.matrices = NULL)).

Please double check.

**Comment by M-E-Rademaker** [comment]
I think this can be closed for now. Once we approach a bootstrap/resample function (#10 ) we may pick up on the idea again of making the permutateData() function more general, perhaps even integrate it on function.
